import 'package:flutter/cupertino.dart';
import 'package:get/get.dart';

class Mylocal implements Translations {
  @override
  // TODO: implement keys
  Map<String, Map<String, String>> get keys => {
        'ar': {
          'add': 'اضافة',
          'notask': 'لا يوجد لديك أية مهام\nقم بإضافة بعض المهم !',
          'cya': 'تعديل معلوماتك',
          'cyl': 'قم بتغيير اللغة ',
          'ava': 'رقم الآفاتار',
          'save': 'حفظ',
          'title': 'العنوان',
          'note': 'الملاحظة',
          'date': 'التاريخ',
          'stime': 'وقت البدء',
          'etime': 'وقت الانتهاء',
          'remind': 'التذكير',
          'repeat': 'تكرار',
          'color': 'اللون',
          'creat': 'إنشاء',
          'hint': "أدخل شيء",
          'early': 'دقائق مبكرا',
          'name': 'الاسم',
          'hintname': 'أدخل الاسم',
          'av': 'الآفاتار',
          'continue': 'متابعة',
          'confirm': 'هل أنت واثق أنك تريد حذف كل المهام؟',
          'cancel': 'الغاء',
          'delete': 'حذف',
          'welcome': 'مرحبا بك في ارش تودو',
          'new': 'لديك تذكير جديد',
          'hello': 'مرحبا',
          'desc': 'الوصف',
          'ah': 'أضف مهمة',
          'today': 'اليوم',
          'ln': 'ar',
          'taskCompleted': 'تم تنفيذ المهمة ',
          'deleteTask': 'حذف المهمة',
          'requier': 'مطلوب',
          'requierd': 'الرجاء ملئ جميع الحقول',
        },
        'en': {
          'add': '+AddTask',
          'notask':
              'You do not have any tasks yet!\n Add new tasks to make your days productive.',
          'cya': 'Change your information',
          'cyl': 'Change your Language',
          'ava': 'Avatar',
          'save': 'Save',
          'title': 'Title',
          'note': 'Note',
          'date': 'Date',
          'stime': 'Start Time',
          'etime': 'End Time',
          'remind': 'Reminder',
          'repeat': 'Repeat',
          'color': 'Color',
          'creat': 'Create',
          'hint': 'Enter Something',
          'early': 'Minutes Early',
          'name': 'Name',
          'hintname': 'Enter Your Name',
          'av': 'Avatar',
          'continue': 'Continue',
          'confirm': 'Are you sure you want to delete all task?',
          'delete': 'Delete',
          'cancel': 'Cancel',
          'welcome': 'Welcome to Todo ARSH',
          'new': 'You have a new reminder',
          'hello': 'Hello',
          'desc': 'Description',
          'ah': 'Add a Task',
          'today': 'Today',
          'ln': 'en',
          'taskCompleted': 'Task Completed',
          'deleteTask': 'Delete Task',
          'requier': 'Requierd',
          'required': 'Please fill all fieldes',
        }
      };
}
